file-upload:
  environment:
    UPLOAD_DIRECTORY: '/tmp'
    UPLOAD_URL: 'http://file-upload.${STACK_NAME}.${TRAEFIK_DOMAIN}'
    ALLOW_BASIC_AUTH: 'true'
  log_driver: json-file
  tty: true
  log_opt: { max-size: '50m', max-file: '2' }
  image: registry.opus.webadeo.net/file-upload:${FILE_UPLOAD_TAG}
  stdin_open: true
  labels:
    io.rancher.container.pull_image: always
    traefik.enable: ${TRAEFIK_ENABLE}
    traefik.port: 4000
    traefik.domain: ${TRAEFIK_DOMAIN}
