version: '2'
volumes:
  vol-letsencrypt:
    driver: ${STORAGEDRIVER}
services:
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.3.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: ${AWSID_LETSENCRYPT}
      AWS_SECRET_KEY: ${AWSKEY_LETSENCRYPT}
      CERT_NAME: ${CUSTOMERDOMAIN}-letsencrypt
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: ${CUSTOMERDOMAIN}.ftscloud.ch
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: info@ftsystems.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
      - vol-letsencrypt:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
  proxy:
    image: ftsystems/haproxy-customer:0.0.1
    environment:
      HAPROXY_NEXTCLOUD_SERVER: ${NEXTCLOUDSERVER}
      HAPROXY_SSL_CERT: /cert/${CUSTOMERDOMAIN}-letsencrypt/fullchain.pem
      HAPROXY_SSL_KEY: /cert/${CUSTOMERDOMAIN}-letsencrypt/privkey.pem
      HAPROXY_SSL_COMBINED: /cert/${CUSTOMERDOMAIN}-letsencrypt/combined.pem
      HAPROXY_SSL_CREATE: ''
      HAPROXY_SSL_CNAME: ''
      HAPROXY_LOG_ADDRESS: /rsyslog/dev/log
    volumes:
      - vol-letsencrypt:/cert
    volumes_from:
      - rsyslogd
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: rsyslogd
  route53-setup:
    image: ftsystems/route53-customer:latest
    environment:
      RECORD_NAME: ${CUSTOMERDOMAIN}.ftscloud.ch
      RECORD_VALUE: ${DNS_VALUE}
      DNS_ZONE: ${DOMAIN_ID}
      AWS_ACCESS_KEY_ID: ${AWSID_ROUTE53}
      AWS_SECRET_ACCESS_KEY: ${AWSKEY_ROUTE53}
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
  rsyslogd:
    image: ftsystems/rsyslogd:latest
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
    labels:
      io.rancher.container.pull_image: always
