version: '2'
volumes:
  vol-letsencrypt:
    driver: ${STORAGEDRIVER}
services:
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.3.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: ${AWSID}
      AWS_SECRET_KEY: ${AWSKEY}
      CERT_NAME: ${CUSTOMERDOMAIN}-letsencrypt
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: ${CUSTOMERDOMAIN}.ftscloud.ch
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: info@ftsystems.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
      - vol-letsencrypt:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
  proxy:
    image: ftsystems/haproxy-customer:0.0.1
    environment:
      HAPROXY_NEXTCLOUD_SERVER: ${NEXTCLOUDSERVER}
      HAPROXY_SSL_CERT: /cert/${CUSTOMERDOMAIN}-letsencrypt/fullchain.pem
      HAPROXY_SSL_KEY: /cert/${CUSTOMERDOMAIN}-letsencrypt/privkey.pem
      HAPROXY_SSL_COMBINED: /cert/${CUSTOMERDOMAIN}-letsencrypt/combined.pem
      HAPROXY_SSL_CREATE: ''
      HAPROXY_SSL_CNAME: ''
    volumes:
      - vol-letsencrypt:/cert
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
