version: '2'
services:
  app:
    image: koda/docker-knowledge
    volumes:
      - /home/rancher/knowledge/knowledge:/root/.knowledge
    ports:
      - "${knowledge_port}:8080"
    restart: always
    depends_on:
      - "db"
  db:
    image: postgres:9
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_pass}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - /home/rancher/knowledge/postgres/data:/var/lib/postgresql/data
    ports:
      - "${postgres_port}:5432"
    restart: always